--cliente código y nombre / fecha / tipo y numero de pedido / importe total sin impuestos

SELECT NPCA_CLIENTE AS [COD CLIENTE],
CLIE_NOMBRE AS [NOMBRE CLIENTE],
NPCA_FEC_ENT_BASE AS [FECHA DE ENTREGA],
NPCA_TIPO_NPCA AS [TIPO NOTA DE PEDIDO],
NPCA_NUMERO_NPCA AS [NRO NOTA DE PEDIDO],
CLIE_VENDEDOR AS [VENDEDOR DEL CLIENTE],
NPCA_IMP_BRU_ORI AS [IMPORTE TOTAL SIN IMPUESTOS]
FROM VENT_NPCA
INNER JOIN CCOB_CLIE ON NPCA_CLIENTE = CLIE_CLIENTE
INNER JOIN SEGU_USUA ON NPCA_USUARIO_APROB = USUA_USUARIO
INNER JOIN SEGU_AUDI ON AUDI_USUARIO = USUA_USUARIO
INNER JOIN VENT_AUCV ON AUCV_AUDITOR = AUDI_AUDITOR


